force-app/main/default/objects/MockMock__c/MockMock__c.object-meta.xml
<CustomObject>
    <description>Child to Mock.</description>
    <label>MockMock</label>
    <nameField>
        <label>MockMock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MockMocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MockMock__c/fields/isChecked__c.field-meta.xml
<CustomField>
    <fullName>isChecked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks if the MockMock has been checked.</description>
    <label>Checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Invocable_MockMockCheckService.cls
public class Invocable_MockMockCheckService {

    @InvocableMethod(
        label='Checks MockMocks' 
        description='Updates a MockMock__c record with a simple check.')
    public static List<MockMock__C> checkMockMock(List<MockMock__c> lMockMocks) {
        System.debug('Number of Mocks:' + lMockMocks.size());
    
        for (MockMock__c MockMock : (List<MockMock__c>) lMockMocks) {
            MockMock.isChecked__c = true;
        }
        
        update lMockMocks;    
        
        return lMockMocks;
    }
}