force-app/main/default/objects/Mock__c/Mock__c.object-meta.xml
<CustomObject>
    <description>Empty object to test trigger behaviour for logger</description>
    <label>Mock</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MockMock__c/MockMock__c.object-meta.xml
<CustomObject>
    <description>Child to Mock.</description>
    <label>MockMock</label>
    <nameField>
        <label>MockMock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MockMocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MockMock__c/fields/ParentMock__c.field-meta.xml
<CustomField>
    <fullName>ParentMock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Mock</description>
    <inlineHelpText>Parent Mock</inlineHelpText>
    <label>Mock</label>
    <referenceTo>Mock__c</referenceTo>
    <relationshipLabel>MockMocks</relationshipLabel>
    <relationshipName>MockMocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Invocable_MockMockService.cls
public class Invocable_MockMockService {

    @InvocableVariable(
        label='Save the MockMocks?' 
        description='Indicates if the MockMock records should be written to the DB or returned without saving' 
        required=false)
    public boolean doSave;
    
    @InvocableMethod(
        label='create MockMocks' 
        description='Inserts a MockMock__c record for each Mock__c passed into the method.')
    public static List<MockMock__C> createMockMock(List<Mock__c> lMocks) {
        System.debug('Number of Mocks:' + lMocks.size());
    
        List<MockMock__c> newMockMocks = new List<MockMock__c>();
        
    	for (mock__c mock : (List<Mock__c>) lMocks) {
            MockMock__c mockmock = new MockMock__c(
                Name = mock.Name, 
                ParentMock__c = mock.Id);
            newMockMocks.add(mockmock);
        }
        
        //if (doSave == true) {
        	insert newMockMocks;    
        //}
        
        return newMockMocks;
    }
}